apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - Read
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "{{ .Values.efs.id }}"