apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
data:
  cluster.name: {{ .Values.clustername.name }}
  http.server: "On"
  http.port: "2020"
  read.head: "Off"
  read.tail: "On"
  logs.region: "us-west-2"