apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksite-nginx-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ksite-nginx-deployment
  template:
    metadata:
      labels:
        app: ksite-nginx-deployment
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: efs-volume
          mountPath: /usr/share/nginx/html
    volumes:
    - name: efs-volume
      persistentVolumeClaim:
        claimName: efs-pvc