name: Tests and Integration

on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@master

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: Terraform Initilialize
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    #Helm Tests
    - name: Set up Helm
      uses: azure/setup-helm@v3
    
    - name: Helm Lint
      run: helm lint .
      working-directory: ./helm/k-site
    
  #Continuous Delivery
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@master

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: install mkdocs
      run: pip install mkdocs
    
    - name: mkdocs build
      run: mkdocs build
      working-directory: ./mkdocs/my-project

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET}}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: ./mkdocs/my-project/site
      

    


  